---
## WAKE ON LAN SWITCH - COMPONENT
# https://www.home-assistant.io/integrations/wake_on_lan/

- platform: wake_on_lan
  mac: !secret server_mac_address
  name: !secret server_service_name
  host: !secret server_ip_address
  broadcast_address: !secret server_broadcast
  turn_off:
    service: switch.turn_off
    entity_id: switch.server_off

# COMMAND LINE SWITCH - COMPONENT
# https://www.home-assistant.io/integrations/switch.command_line/

- platform: command_line
  switches:
    server_off:
      command_on: switch.home_server
      command_off: !secret server_off_cmd