---
## Template Sensor
# https://www.home-assistant.io/integrations/template/

# Mobile Device States Template#

- platform: template
  sensors:
    # Pixel 4 XL
    pixel_4_battery:
      friendly_name: 'Battery'
      value_template: '{{state_attr("device_tracker.pixel_4_xl",
      "battery_level")}}'
      unit_of_measurement: '%'
    pixel_4_gps_status:
      friendly_name: 'GPS'
      value_template: '{{state_attr("device_tracker.pixel_4_xl",
      "gps_accuracy")}}'
    pixel_4_speed_status:
      friendly_name: 'Speed'
      value_template: '{{state_attr("device_tracker.pixel_4_xl",
      "speed")}}'
    # Pixel
    pixel_battery:
      friendly_name: 'battery'
      value_template: '{{state_attr("device_tracker.pixel",
      "battery_level")}}'
      unit_of_measurement: '%'
    pixel_gps_status:
      friendly_name: 'GPS'
      value_template: '{{state_attr("device_tracker.pixel",
      "gps_accuracy")}}'
    pixel_speed_status:
      friendly_name: 'Speed'
      value_template: '{{state_attr("device_tracker.pixel",
      "speed")}}'
