## UnRAID Version Sensor URLs
# Stable URL: https://s3.amazonaws.com/dnld.lime-technology.com/stable/unRAIDServer.plg
# Beta URL: https://s3.amazonaws.com/dnld.lime-technology.com/next/unRAIDServer.plg

- platform: command_line
  name: Unraid Version (Next)
  command: /usr/bin/curl --insecure "https://s3.amazonaws.com/dnld.lime-technology.com/next/unRAIDServer.plg" 2>&1 | grep Version |awk '{print $3}'

- platform: snmp
  host: 10.0.20.2
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1


## API sensors

- platform: template
  sensors:
    unraid_array_status:
      friendly_name: UnRAID Array Status
      value_template: '{{state_attr("binary_sensor.chsunr01_server", "arrayStatus")}}'

    unraid_array_protection:
      friendly_name: UnRAID Array Protection
      value_template: '{{state_attr("binary_sensor.chsunr01_server", "arrayProtection")}}'

    unraid_array_space:
      friendly_name: UnRAID Array Space
      value_template: >
        {{ state_attr("binary_sensor.chsunr01_server", "diskSpace")
          | regex_findall_index(".*\((\d+.?\d+) %\)") | float }}
      unit_of_measurement: '%'


- platform: snmp
  name: 'UnRAID uptime'
  host: 10.0.20.2
  port: 161
  community: public
  version: 1
  baseoid: 1.3.6.1.2.1.1.3.1
  accept_errors: true
  unit_of_measurement: 'minutes'


#
#ifDescr.13 Intel Corporation 82580 Gigabit Network Connection
#ifDescr.14 Intel Corporation 82580 Gigabit Network Connection
#ifDescr.15 Intel Corporation 82580 Gigabit Network Connection
#ifDescr.16 Intel Corporation 82580 Gigabit Network Connection
#ifDescr.17 Intel Corporation Ethernet Connection (2) I219-V