sensor:

# Downstairs Average LUX
  - platform: min_max
    type: mean
    name: downstairs_average_lux
    entity_ids:
      - sensor.kitchen_hue_sensor_lux
      - sensor.living_room_hue_sensor_lux
      - sensor.bathroom_lux
      - sensor.hall_hue_sensor_lux

# Upstairs Average LUX
  - platform: min_max
    type: mean
    name: upstairs_average_lux
    entity_ids:
      - sensor.landing_hue_sensor_lux
      - sensor.office_hue_lux
      - sensor.bedroom_hue_sensor_lux
      - sensor.craft_room_hue_lux