---
# HOME ASSISTANT CONFIGURATION YAML

homeassistant:
  customize: !include customize.yaml

# HOME ASSISTANT FRONTEND CONFIGURATION

frontend:
  themes: !include themes.yaml
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/fontawesome/hass-fontawesome-solid.html
    - /local/custom_ui/fontawesome/hass-fontawesome-regular.html
    - /local/custom_ui/fontawesome/hass-fontawesome-brands.html

# HOME ASSISTANT CONFIGURATION

config:

default_config:

recorder:
  purge_interval: 2
  purge_keep_days: 5

logger:
  default: error
#  logs:
#    homeassistant.components.scrape: debug

system_log:
  fire_event: true

lovelace:
  mode: yaml

# HOME ASSISTANT COMUNITY UPDATER - Component

hacs:
  token: !secret access_token

# (UniFI) GENERIC CAMERA - Component

stream:

camera:
  - platform: generic
    name: Back Garden
    still_image_url: !secret still_image_url
    stream_source: !secret rtsp_stream_source
    verify_ssl: !secret verify_ssl

# CIRCADIAN LIGHTING - Component
# https://community.home-assistant.io/t/circadian-lighting-custom-component/61246

circadian_lighting:

# WEATHER - Component


weather:
  - platform: darksky
    api_key: !secret dark_sky_api

sun:


# GOOGLE CALENDAR - Component

google:
  client_id: !secret google_calendar_id
  client_secret: !secret google_calendar_secret

# NEST SMART HOME - Intergration

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# GOOGLE - TTS

tts:
  - platform: google_translate
    service_name: google_say

# SPEEDTEST.NET

speedtestdotnet:
  server_id: !secret speedtest_server_id
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# WEMO - Smart Plugs

wemo:
  discovery: false
  static:
    - !secret wemo_0_ip_address
    - !secret wemo_1_ip_address

# TPLINK - Smart Plugs

tplink:
  discovery: true
  switch:
    - host: !secret tplink_0_ip_address

# Utility Meter

utility_meter:
  monthly_cabinet:
    source: sensor.cabinet_consumption
    cycle: monthly
  monthly_xmas_lights:
    source: sensor.xmas_lights_consumption
    cycle: monthly

# INCLUDES

automation: !include_dir_merge_list custom_config/automations
binary_sensor: !include_dir_merge_list custom_config/binary_sensor
intent_script: !include_dir_merge_list custom_config/intents
media_player: !include_dir_merge_list custom_config/media_player
sensor: !include_dir_merge_list custom_config/sensors
switch: !include_dir_merge_list custom_config/switch

group: !include custom_config/includes/group.yaml
input_boolean: !include custom_config/includes/input_boolean.yaml
input_select: !include custom_config/includes/input_select.yaml
light: !include custom_config/includes/light_groups.yaml
nzbget: !include custom_config/includes/nzbget.yaml
scene: !include scenes.yaml
script: !include custom_config/includes/scripts.yaml
zone: !include custom_config/includes/zone.yaml
