homeassistant:
  packages: !include_dir_named packages/
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml


input_text:
  card_containers:
    initial: Containers
  software_version:
    initial: Version'
  unraid_usb:
    initial: USB Storage
  devices_on:
    initial: Devices On
  plugs_on:
    initial: Plugs On


automation: !include_dir_merge_list ../../../areas/
binary_sensor: !include_dir_merge_list ../../../areas/
input_number: !include_dir_merge_list ../../../areas/
sensor: !include_dir_merge_list ../../../areas/
switch: !include_dir_merge_list ../../../areas/
media_player: !include_dir_merge_list ../../../areas/
script: !include_dir_merge_list ../../../areas/
scene: !include_dir_merge_list ../../../areas/
#group: !include_dir_merge_list ../../../areas/






#input_boolean: !include_dir_list ../../../areas/

#light: !include_dir_merge_list configuration/lights/

