# Custom Header with some custom configuration (https://github.com/maykar/custom-header)
custom_header:
  !include dwains-theme/plugins/custom_header/configuration.yaml
      
# Button Card Templates folder (https://github.com/custom-cards/button-card#Configuration-Templates)
# These are the templates used to avoid too much duplicate code.      
button_card_templates:
  !include_dir_merge_named dwains-theme/plugins/button-cards-templates        

# Start of main lovelace theme 
background: var(--background-image)
views:
  !include_dir_merge_list dwains-theme/views/main/

