title: Home
views:
  - path: default_view
    title: Home
    cards:
      - type: picture-entity
        entity: binary_sensor.front_door_camera_path_activity
        camera_image: camera.front_door
        camera_view: live
        show_name: false
        show_state: false
        tap_action:
          action: none
        hold_action:
          action: none

