automation:
  # Kitchen - Philips Hue Dimmer

  - alias: 'Kitchen turn-on from dimmer normal'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_switch
        event: 1002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.kitchen
          brightness: 249

  - alias: 'Kitchen increase brightness from dimmer'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_switch
        event: 2002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.kitchen
          brightness: >
            {% set bri = state_attr
            ('light.kitchen', 'brightness') | int %}
            {{ [bri+30, 249] | min }}

  - alias: 'Kitchen decrease brightness from dimmer'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_switch
        event: 3002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.kitchen
          brightness: >
            {% set bri = state_attr
            ('light.kitchen', 'brightness') | int %}
            {{ [bri-30, 10] | max }}

  - alias: 'Kitchen turn-off from dimmer'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_switch
        event: 4000
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.kitchen