automation:

  # Craft Room - Philips Hue Dimmer
  - alias: 'Craft Room turn-on from dimmer normal'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: craft_room_switch
        event: 1002
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.craft_room_shadow
          brightness_pct: 50

  - alias: 'Craft Room turn-on from dimmer bright'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: craft_room_switch
        event: 1001
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.craft_room
          brightness_pct: 100

  - alias: 'Craft Room increase brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: craft_room_switch
        event: 2002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.craft_room_shadow
          brightness: >
            {% set bri = state_attr
            ('light.craft_room_shadow', 'brightness') | int %}
            {{ [bri+30, 249] | min }}

  - alias: 'Craft Room decrease brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: craft_room_switch
        event: 3002
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.craft_room_spots
      - service: light.turn_on
        data_template:
          entity_id: light.craft_room_shadow
          brightness: >
            {% set bri = state_attr
            ('light.craft_room_shadow', 'brightness') | int %}
            {{ [bri-30, 10] | max }}

  - alias: 'Craft Room turn-off from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: craft_room_switch
        event: 4000
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.craft_room