# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/dynamic_page.html
# Enabling this page by uncommenting the code below. It will result in a dynamic page but it will override the camera page!

#dynamic_page:
#  addon:
#    name: Hello dynamic page
#    icon: fas:puzzle-piece
#    path: 'dwains-theme/addons/dynamic_page/hello-dynamic-page/page.yaml'
#     data:
#       some_data: 'This is some data parsed.'
#       some_other_data: 'and some other data.'

more_page:
  addons:
    - name: Media
      icon: fas:tv
      path: 'dwains-theme/addons/more_page/media_players/media.yaml'