---
###############################################################################
#                                                                             #
#                                Template Sensor                              #
#                                                                             #
###############################################################################

# https://www.home-assistant.io/integrations/template/

#################################################################
#                                                               #
#                      UniFI Presense States Template           #
#                                                               #
#################################################################

- platform: template
  sensors:
    user_1_connected_ap:
      friendly_name: !secret user_1_phone
      value_template: >
        {% if is_state("device_tracker.pixel_4_xl", "home") %}
        {% if is_state_attr("device_tracker.pixel_4_xl",
        "ap_mac", "b4:fb:e4:21:79:1c") %}
          OFFICE_WIFI

        {% elif is_state_attr("device_tracker.pixel_4_xl",
        "ap_mac", "78:8a:20:4b:09:83") %}
          LIVING_ROOM_WIFI

        {% else %}
          Offline
        {% endif %}
        {% else %}
          Offline
        {% endif %}
    user_2_connected_ap:
      friendly_name: !secret user_2_phone
      value_template: >
        {% if is_state("device_tracker.pixel", "home") %}
        {% if is_state_attr("device_tracker.pixel",
        "ap_mac", "b4:fb:e4:21:79:1c") %}
          OFFICE_WIFI

        {% elif is_state_attr("device_tracker.pixel",
        "ap_mac", "78:8a:20:4b:09:83") %}
          LIVING_ROOM_WIFI

        {% else %}
          Offline
        {% endif %}
        {% else %}
          Offline
        {% endif %}
