sensor:

# Glances Addon
  - platform: rest
    resource: !secret glances_rest_url
    name: Glances Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# VSCode Addon
  - platform: rest
    resource: !secret vscode_rest_url
    name: VSCode Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# ESPHome Addon
  - platform: rest
    resource: !secret esphome_rest_url
    name: ESPHome Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# PHPMyAdmin Addon
  - platform: rest
    resource: !secret phpmyadmin_rest_url
    name: PHPMyAdmin Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# ADB Addon
  - platform: rest
    resource: !secret adb_rest_url
    name: ADB Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# AdGaurd Addon
  - platform: rest
    resource: !secret adgaurd_rest_url
    name: AdGaurd Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# Deconz Addon
  - platform: rest
    resource: !secret deconz_rest_url
    name: Deconz Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# Mosquitto Addon
  - platform: rest
    resource: !secret mosquitto_rest_url
    name: Mosquitto Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# SSH & Terminal Addon
  - platform: rest
    resource: !secret ssh_and_terminal_rest_url
    name: SSH and Terminal Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# MariaDB Addon
  - platform: rest
    resource: !secret mariadb_rest_url
    name: MariaDB Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

# Node-Red Addon
  - platform: rest
    resource: !secret node_red_rest_url
    name: Node-Red Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - last_version

  - platform: rest
    resource: !secret vscode_rest_url
    name: VSCode Addon
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret access_token
      Content-Type: application/json
#    json_attributes_path: "$.data"
#    json_attributes:
#      - version
#      - last_version

switch:
  - platform: template
    switches:

      glances_addon:
        value_template: "{{ is_state('sensor.glances_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_glances
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_glances

      vscode_addon:
        value_template: "{{ is_state('sensor.vscode_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_vscode
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_vscode

      esphome_addon:
        value_template: "{{ is_state('sensor.esphome_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: 15ef4d2f_esphome
        turn_off:
          service: hassio.addon_stop
          data:
            addon: 15ef4d2f_esphome

      phpmyadmin_addon:
        value_template: "{{ is_state('sensor.phpmyadmin_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_phpmyadmin
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_phpmyadmin

      adb_addon:
        value_template: "{{ is_state('sensor.adb_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_adb
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_adb

      adguard_addon:
        value_template: "{{ is_state('sensor.adguard_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_adguard
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_adguard

      deconz_addon:
        value_template: "{{ is_state('sensor.deconz_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: core_deconz
        turn_off:
          service: hassio.addon_stop
          data:
            addon: core_deconz

      mosquitto_addon:
        value_template: "{{ is_state('sensor.mosquitto_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: core_mosquitto
        turn_off:
          service: hassio.addon_stop
          data:
            addon: core_mosquitto

      ssh_and_terminal_addon:
        value_template: "{{ is_state('sensor.ssh_and_terminal_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: core_ssh
        turn_off:
          service: hassio.addon_stop
          data:
            addon: core_ssh

      mariadb_addon:
        value_template: "{{ is_state('sensor.mariadb_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: core_mariadb
        turn_off:
          service: hassio.addon_stop
          data:
            addon: core_mariadb

      node_red_addon:
        value_template: "{{ is_state('sensor.node_red_addon', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_nodered
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_nodered
