---
sensor:

## Home Assistant Build In Weather
# https://www.home-assistant.io/integrations/yr/

  - platform: yr


## SYSTEM DETAILS
# Version Sensor
# https://www.home-assistant.io/integrations/version/

  - platform: version

# Time & Date
# https://www.home-assistant.io/integrations/time_date/

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat
