automation:

  # Bathroom - Philips Hue Dimmer

  - alias: 'Bathroom turn-on from dimmer normal'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bathroom_switch
        event: 1002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bathroom
          brightness: 249

  - alias: 'Bathroom increase brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bathroom_switch
        event: 2002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bathroom
          brightness: >
            {% set bri = state_attr
            ('light.bathroom', 'brightness') | int %}
            {{ [bri+30, 249] | min }}

  - alias: 'Bathroom decrease brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bathroom_switch
        event: 3002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bathroom
          brightness: >
            {% set bri = state_attr
            ('light.bathroom', 'brightness') | int %}
            {{ [bri-30, 10] | max }}

  - alias: 'Bathroom turn-off from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bathroom_switch
        event: 4000
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.bathroom
