automation:

  #  Bathroom - Philips Hue Motion
  - alias: 'Bathroom lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on'
    condition:
      - condition: state
        entity_id: light.bathroom
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.bathroom_lux
        below: '1.2'
      - condition: or
        conditions:
        - condition: state
          entity_id: person.abi
          state: home
        - condition: state
          entity_id: person.toby
          state: home
    action:
      service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness: 249

  - alias: 'Bathroom lights turn off when no motion sensor'
    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'off'
      for:
        minutes: 3
    condition:
    - condition: state
      entity_id: binary_sensor.bathroom_door_open_close
      state: 'on'
    action:
      service: light.turn_off
      data:
        entity_id: light.bathroom
        transition : 10

  - alias: 'Bathroom lights turn off when door open and no motion'
    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_door_open_close
      to: 'on'
      for:
        seconds: 10
    condition:
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'off'
      for:
        seconds: 10
    action:
      service: light.turn_off
      data:
        entity_id: light.bathroom
        transition : 10