sensor:

## GOOGLE MAPS
# GOOGLE GEOCODE -  CUSTOM COMPONENT
# https://github.com/gregoryduckworth/GoogleGeocode-HASS
  - platform: google_geocode
    name: geocode_user_2
    origin: !secret geocode_device_tracker_2
    options: street_number, street, city
    display_zone: show
    api_key: !secret geocode_api_key
    scan_interval: 600

# GOOGLE TRAVEL TIME - COMPONENT
# https://www.home-assistant.io/integrations/google_travel_time/
  - platform: google_travel_time
    name: user_2_to_home
    api_key: !secret geocode_api_key
    origin: !secret user_2_device_tracker
    destination: zone.home
    scan_interval: 600

## Template Sensor
# https://www.home-assistant.io/integrations/template/

# Mobile Device States Template#

  - platform: template
    sensors:
      # Pixel
      pixel_battery:
        friendly_name: 'battery'
        value_template: '{{state_attr("device_tracker.pixel",
        "battery_level")}}'
        unit_of_measurement: '%'
      pixel_gps_status:
        friendly_name: 'GPS'
        value_template: '{{state_attr("device_tracker.pixel",
        "gps_accuracy")}}'
      pixel_speed_status:
        friendly_name: 'Speed'
        value_template: '{{state_attr("device_tracker.pixel",
        "speed")}}'
