automation:

#  Office - Philips Hue Motion
  - alias: 'Office lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.office_hue_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.office_hue_lux
        below: '1.2'
      - condition: or
        conditions:
        - condition: state
          entity_id: person.abi
          state: 'home'
        - condition: state
          entity_id: person.toby
          state: 'home'
    action:
      service: light.turn_on
      data:
        entity_id: light.office
        brightness: 249

  - alias: 'Office lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.office_hue_motion
      to: 'off'
      for:
        minutes: 30
    condition:
      - condition: state
        entity_id: device_tracker.chsdt01
        state: 'not_home'
    action:
      service: light.turn_off
      data:
        entity_id: light.office
        transition: 10



group:
  office_lights:
    name: Office Lights
    entities:
      - light.office_spot_01
      - light.office_spot_02
      - light.office_desk

# Light Groups
light:
  - platform: group
    name: Office
    entities:
      - light.office_spot_01
      - light.office_spot_02
      - light.office_desk