---
## SYSTEM DETAILS
# Version Sensor
# https://www.home-assistant.io/integrations/version/

- platform: version

# Time & Date
# https://www.home-assistant.io/integrations/time_date/

- platform: time_date
  display_options:
    - time
    - date
    - date_time
    - time_date
    - time_utc
    - beat

# UNIFI MONITORING - CUSTOM COMPONENT
# https://github.com/custom-components/sensor.unifigateway

- platform: unifigateway
  host: !secret unifi_host
  username: !secret unifi_username
  password: !secret unifi_password
  monitored_conditions:
    - lan
    - wlan
    - alerts
    - firmware

# MariaDB Size Sensor
- platform: sql
  db_url: !secret db_url
  queries:
    - name: 'Home Assistant DB size'
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant_db" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB
