---
#  Office - Philips Hue Dimmer

- alias: 'Toggle Office from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness: 249

- alias: 'Increase brightness of office from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness: >
          {% set bri = state_attr('light.office', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of office from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness: >
          {% set bri = state_attr('light.office', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# Bedroom - Philips Hue Dimmer

- alias: 'Turn on bedroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom
        brightness: 249

- alias: 'Increase brightness of bedroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lamp
        brightness: >
          {% set bri = state_attr('light.bedroom_lamp', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of bedroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 3002
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.bedroom_pendants
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lamp
        brightness: >
          {% set bri = state_attr('light.bedroom_lamp', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Turn off Bedroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.bedroom

# Craft Room - Philips Hue Dimmer

- alias: 'Turn on living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.craft_room
        brightness: 249

- alias: 'Increase brightness of living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.craft_room_shadow
        brightness: >
          {% set bri = state_attr('light.craft_room_shadow', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 3002
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.craft_room_spots
    - service: light.turn_on
      data_template:
        entity_id: light.craft_room_shadow
        brightness: >
          {% set bri = state_attr('light.craft_room_shadow', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Turn off living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.craft_room

# Living Room - Philips Hue Dimmer

- alias: 'Turn on living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        brightness: 249

- alias: 'Increase brightness of living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_lamps
        brightness: >
          {% set bri = state_attr('light.living_room_lamps', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 3002
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.living_room_pendant
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_lamps
        brightness: >
          {% set bri = state_attr('light.living_room_lamps', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Turn off living room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.living_room

# Kitchen - Philips Hue Dimmer

- alias: 'Turn on kitchen from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: 249

- alias: 'Increase brightness of kitchen from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: >
          {% set bri = state_attr('light.kitchen', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of kitchen from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: >
          {% set bri = state_attr('light.kitchen', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Turn off kitchen from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.kitchen

# Bathroom - Philips Hue Dimmer

- alias: 'Turn on bathroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom
        brightness: 249

- alias: 'Increase brightness of bathroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom
        brightness: >
          {% set bri = state_attr('light.bathroom', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of bathroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom
        brightness: >
          {% set bri = state_attr('light.bathroom', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Turn off bathroom from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.bathroom
