---
#  Office - Philips Hue Motion
- alias: 'Office turn-on lights'
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: light.office
    state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.office
      brightness: 249

- alias: 'Office motion sensor turn-off lights'
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'off'
    for:
      minutes: 60
  condition:
  - condition: state
    entity_id: binary_sensor.office_window
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.office
      transition : 5

#  Bathroom - Philips Hue Motion
- alias: 'Bathroom turn-on lights'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: light.bathroom
    state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom
      brightness: 249

- alias: 'Bathroom motion sensor turn-off lights'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for:
      minutes: 3
  condition:
  - condition: state
    entity_id: binary_sensor.bathroom_door
    state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition : 10

- alias: 'Bathroom door Sensor turn-off lights'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
    to: 'on'
    for:
      seconds: 10
  condition:
  - condition: state
    entity_id: binary_sensor.bathroom_motion
    state: 'off'
    for:
      seconds: 10
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition : 10
