---
#  Office - Philips Hue Dimmer

- alias: 'Office turn-on from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office
        brightness_pct: 50


- alias: 'Office turn-on from dimmer bright'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office
        brightness_pct: 100

- alias: 'Office increase brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness: >
          {% set bri = state_attr
          ('light.office', 'brightness') | int %}
          {{ [bri+15, 249] | min }}

- alias: 'Office decrease brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness: >
          {% set bri = state_attr
          ('light.office', 'brightness') | int %}
          {{ [bri-15, 10] | max }}

- alias: 'Office stop brightness from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: office_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: office_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.office
        field: "/action"
        data: {"bri_inc":0}

- alias: 'Office turn-off from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
          - light.office

# Bedroom - Philips Hue Dimmer

- alias: 'Bedroom turn-on from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bedroom_lamp
        brightness_pct: 50

- alias: 'Bedroom turn-on from dimmer bright'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bedroom
        brightness_pct: 100

- alias: 'Bedroom increase brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lamp
        brightness: >
          {% set bri = state_attr
          ('light.bedroom_lamp', 'brightness') | int %}
          {{ [bri+15, 249] | min }}

- alias: 'Bedroom decrease brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 3002
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.bedroom_pendants
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lamp
        brightness: >
          {% set bri = state_attr
          ('light.bedroom_lamp', 'brightness') | int %}
          {{ [bri-15, 10] | max }}

- alias: 'Bedroom stop brightness from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.bedroom_lamp
        field: "/action"
        data: {"bri_inc":0}

- alias: 'Bedroom turn-off from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
          - light.bedroom

# Craft Room - Philips Hue Dimmer
- alias: 'Craft Room turn-on from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.craft_room_shadow
        brightness_pct: 50

- alias: 'Craft Room turn-on from dimmer bright'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.craft_room
        brightness_pct: 100

- alias: 'Craft Room increase brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.craft_room_shadow
        brightness: >
          {% set bri = state_attr
          ('light.craft_room_shadow', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Craft Room decrease brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 3002
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.craft_room_spots
    - service: light.turn_on
      data_template:
        entity_id: light.craft_room_shadow
        brightness: >
          {% set bri = state_attr
          ('light.craft_room_shadow', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Craft Room turn-off from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: craftroom_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.craft_room

# Living Room - Philips Hue Dimmer

- alias: 'Living Room turn-on from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.living_room_lamps
        brightness_pct: 50
    - service: light.turn_on
      data:
        entity_id:
          - light.living_room_strip
        brightness_pct: 20

- alias: 'Living Room turn-on from dimmer bright'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.living_room
        brightness_pct: 100

- alias: 'Living Room increase brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_lamps
        brightness: >
          {% set bri = state_attr
          ('light.living_room_lamp', 'brightness') | int %}
          {{ [bri+15, 249] | min }}
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_strip
        brightness: >
          {% set bri = state_attr
          ('light.living_room_strip', 'brightness') | int %}
          {{ [bri+15, 249] | min }}

- alias: 'Living Room decrease brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 3002
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.bedroom_pendants
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_lamps
        brightness: >
          {% set bri = state_attr
          ('light.living_room_lamps', 'brightness') | int %}
          {{ [bri-15, 10] | max }}
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_strip
        brightness: >
          {% set bri = state_attr
          ('light.living_room_strip', 'brightness') | int %}
          {{ [bri-15, 10] | max }}

- alias: 'Living Room stop brightness from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.living_room_lamps
        field: "/action"
        data: {"bri_inc":0}
    - service: deconz.configure
      data:
        entity: light.living_room_strip
        field: "/action"
        data: {"bri_inc":0}

- alias: 'Living Room turn-off from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
          - light.living_room

# Kitchen - Philips Hue Dimmer

- alias: 'Kitchen turn-on from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: 249

- alias: 'Kitchen increase brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: >
          {% set bri = state_attr
          ('light.kitchen', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Kitchen decrease brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: >
          {% set bri = state_attr
          ('light.kitchen', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Kitchen turn-off from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.kitchen

# Bathroom - Philips Hue Dimmer

- alias: 'Bathroom turn-on from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom
        brightness: 249

- alias: 'Bathroom increase brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom
        brightness: >
          {% set bri = state_attr
          ('light.bathroom', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Bathroom decrease brightness from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom
        brightness: >
          {% set bri = state_attr
          ('light.bathroom', 'brightness') | int %}
          {{ [bri-30, 10] | max }}

- alias: 'Bathroom turn-off from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 4000
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.bathroom
