automation:

  # Bedroom - Philips Hue Dimmer
  - alias: 'Bedroom turn-on from dimmer normal'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 1002
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.bedroom_lamp_01
          brightness_pct: 50

  - alias: 'Bedroom turn-on from dimmer bright'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 1001
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.bedroom
          brightness_pct: 100

  - alias: 'Bedroom increase brightness from dimmer'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 2002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamp_01
          brightness: >
            {% set bri = state_attr
            ('light.bedroom_lamp_01', 'brightness') | int %}
            {{ [bri+15, 249] | min }}

  - alias: 'Bedroom decrease brightness from dimmer'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 3002
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.bedroom_pendants
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamp_01
          brightness: >
            {% set bri = state_attr
            ('light.bedroom_lamp_01', 'brightness') | int %}
            {{ [bri-15, 10] | max }}

  - alias: 'Bedroom stop brightness from dimmer'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_switch
          event: 2003
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_switch
          event: 3003
    action:
      - service: deconz.configure
        data:
          entity: light.bedroom_lamp_01
          field: "/action"
          data: {"bri_inc":0}

  - alias: 'Bedroom turn-off from dimmer'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 4002
    action:
      - service: light.turn_off
        entity_id:
            - light.bedroom


# Dwains Theme Group
group:
  bedroom_switches:
    name: Bedroom Switches
    entities:
      - switch.bedroom_tv_smart_plug_relay