- platform: template
  sensors: 
    energy_total_usage:
      friendly_name: Total Energy Usage
      unit_of_measurement: kWh
      value_template: >-  
        {{ 
          (states.sensor.sp_lr_amp_total_daily_energy.state | float) +
          (states.sensor.sp_of_cab_total_daily_energy.state | float) +
          (states.sensor.office_pdu_smart_plug_total_daily_energy.state | float) +
          (states.sensor.living_room_tv_smart_plug_total_daily_energy.state | float)
        }}

    power_total_usage:
      friendly_name: Total Power Usage
      unit_of_measurement: W
      value_template: >-  
        {{ 
          (states.sensor.sp_lr_amp_wattage.state | float) +
          (states.sensor.sp_of_cab_wattage.state | float) +
          (states.sensor.office_pdu_smart_plug_wattage.state | float) +
          (states.sensor.living_room_tv_smart_plug_wattage.state | float)
        }}



    daily_energy_cost:
      entity_id: sensor.daily_energy_kwh
      friendly_name: 'Daily Cost'
      value_template: >-
        {% if (states.sensor.daily_energy_kwh.state|float > 0) %}
          {{ (states.sensor.daily_energy_kwh.state|float * 0.2420)|round(2) }}
        {% endif %}

    monthly_energy_cost:
      entity_id: sensor.monthly_energy_kwh
      friendly_name: 'Daily Cost'
      value_template: >-
        {% if (states.sensor.monthly_energy_kwh.state|float > 0) %}
          {{ (states.sensor.monthly_energy_kwh.state|float * 0.2420)|round(2) }}
        {% endif %}

#    monthly_power:
#      friendly_name: Monthly Power
#      unit_of_measurement: kWh
#      value_template: >
#        {{ states("sensor.monthly_power_offpeak")|float + states("sensor.monthly_power_peak")|float }}

#    daily_power_cost:
#      friendly_name: Daily Power
#      unit_of_measurement: £
#      value_template: >
#        {{ (states("sensor.daily_power_offpeak")|float * 0.2307
#            + states("sensor.daily_power_peak")|float * 0.2479) | round(2) }}

#    monthly_power_cost:
#      friendly_name: Monthly Power
#      unit_of_measurement: £
#      value_template: >
#        {{ (states("sensor.monthly_power_offpeak")|float * 0.2307
#            + states("sensor.monthly_power_peak")|float * 0.2479) | round(2) }}

#    daily_energy_fixed_cost:
#      friendly_name: Fixed daily energy cost (gas and power)
#      unit_of_measurement: £
#      entity_id: sensor.date  # To get rid of the warning
#      value_template: >
#        {{ (0.1480 + 0.3554) + (0.1480 + 0.6293) }}

#    monthly_energy_fixed_cost:
#      friendly_name: Fixed daily energy cost (gas and power)
#      unit_of_measurement: £
#      entity_id: sensor.date
#      value_template: >
#        {{ states("sensor.daily_energy_fixed_cost")|float * now().day }}
