---
name: HomeAssistant-CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home_assistant_config_check:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
        with:
          repo-token: ${{ secrets.HA_CONFIG_TOKEN }}
      - uses: actions/checkout@master
      - run: mv secrets.yaml.tmpl secrets.yaml
      - uses: kpucynski/action-ha-config-check@master
        with:
          ha_version: "latest"
        env:
          HASS_EXTRA_ARGS: "-f -s -i"
