name: ha-config-check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Home Assistant Configuration Check
      uses: ludeeus/action-ha-config-check@0.0.1
      with:
        repo-token: ${{ secrets.HA_CONFIG_TOKEN }}
      env:
        ACTION_VERSION: STABLE
        ACTION_CONFIG_PATH: ./configuration.yaml
        ACTION_ALLOW_FAIL: True
